In [2]:
#numpy
import numpy as np
data=np.array([4.5,6.0,1.2,5.4])
print(data*2)

[ 9.  12.   2.4 10.8]


In [3]:
#numpy array dimension
#shape:每一个层级的元素数,且同一维度下的元素长度必须一致
data1=np.array([1,2,3,4])
print(data1.shape)
data2=np.array([[1,2,3],[4,5,6]])
print(np.shape(data2))
data3=np.array([[1,2],[3,4,5]])
print(data3.shape)


(4,)
(2, 3)


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
#indexing arrays
#data[row][column] or data[row,column]
data4=np.array([[9,1],[7,8]])
print(data4[1])
print(data4[0][1])
print(data4[0,1])
'注意！！！与其他row column相反'

[7 8]
1
1


In [ ]:
#numpy element data types
a=[3,2,4]
x=np.array(a,dtype=np.float64)
#For the most part, stick with bool, int64, and float64
x.dtype

numpy methods

In [ ]:
b=np.array([[9,1],[7,8]])
b.T
#.T method 可实现行与列的互换

array([[9, 7],
       [1, 8]])

In [ ]:
b*b
#区别于b=np.array([1]*2),即区分list和array
b+2

array([[11,  3],
       [ 9, 10]])

In [ ]:
#np has its own operation library
np.sqrt(b)
np.sin(b)

array([[0.41211849, 0.84147098],
       [0.6569866 , 0.98935825]])

In [ ]:
#0,1,eye methods' brackets are all (row,column)
#if there is only a integer in the bracket, it only represents the 1D columns
c=np.zeros((2,3))
#等价于np.zeros([2,3])
c=c+1
print(c)
'这个也是先row后column，np.array创建和指引都类数组'

[1. 1. 1.]


In [ ]:
#eye only accepts integer, yield a 
d=np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [ ]:
#numpy index
#无论几维，按第一层级分成不同行
#array[row,:column,]
e=np.array([[9,1],[7,8],[1,1],[5,1]])
print(e[:,1])

[1 8 1 1]


In [ ]:
#tolist可以将array转化为数组
f=np.array([[1,2,3],[4,5,6]])
print(f.tolist())

[[1, 2, 3], [4, 5, 6]]


In [ ]:
#sort函数，默认是1，即每行排序；若sort(0)则每列排序，改变原来，无返回值，同list
#argsort函数，排序后返回排名后的索引(成绩单里的学号)(有返回值)
#numpy是mutable
g=np.array([[1,9],[9,1],[7,8],[8,7]])
print(g.sort(0))
print(g)
print(g.argsort(0))


None
[[1 1]
 [7 7]
 [8 8]
 [9 9]]
[[0 0]
 [1 1]
 [2 2]
 [3 3]]


In [ ]:
#numpy methods - statistics
x.max(i)
#find max in each column if i=0, 
#          in each row if i=1  
#find max of everything in x if nothing
x.min(i)
#find min in each column if i=0, 
#         in each row if i=1  
#find min of everything in x if nothing
x.mean(i)
#find average in each column if i=0, 
#             in each row if i=1  
#find average of everything in x if nothing



NameError: name 'x' is not defined

In [ ]:
#linspace函数：Produce arrays of n points (not  spacing!) from start to finish.
print(np.linspace(0,10,2))
print(np.linspace(0,10,3))#最后一个参数表示一共多少个值
#endpoint = True, include the last point => (finish – start)/(n-1)
#endpoint = False, omit last point => (finish – start)/(n)
#retstep = True, show the interval length between points
print(np.linspace(0,10,2,endpoint=False,retstep=True))

[ 0. 10.]
[ 0.  5. 10.]
(array([0., 5.]), np.float64(5.0))


In [3]:
print(np.linspace(-4,4,11))

[-4.  -3.2 -2.4 -1.6 -0.8  0.   0.8  1.6  2.4  3.2  4. ]
